/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: cleanupdb
 * CMDLEVEL: QCMD_DEV
 * CMDARGS: 0
 * CMDDESC: Clean up database.
 * CMDFUNC: csu_docleanupdb
 * CMDPROTO: int csu_docleanupdb(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: cleanupdb
 * CMDHELP: Removes unused and never used accounts that exceed the idleness
 * CMDHELP: thresholds.
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_docleanupdb(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *vrup, *srup;
  authname *anp;
  int i;
  time_t t;
  long to_age, unused_age;
  int expired = 0, unauthed = 0;

  t = time(NULL);
  to_age = t - (80 * 3600 * 24);  
  unused_age = t - (10 * 3600 * 24);

  for (i=0;i<REGUSERHASHSIZE;i++) {
    for (vrup=regusernicktable[i]; vrup; vrup=srup) {
      srup=vrup->nextbyname;
      if (!(anp=findauthname(vrup->ID)))
        continue; /* should maybe raise hell instead */
        
      if(!anp->nicks && !UHasHelperPriv(vrup) && !UIsCleanupExempt(vrup)) {
        if(vrup->lastauth && (vrup->lastauth < to_age)) {
          expired++;
        } else if(!vrup->lastauth && (vrup->created < unused_age)) {
          unauthed++;
        } else {
          continue;
        }

        cs_removeuser(vrup);
      }
    }
  }
  
  chanservsendmessage(sender, "Cleanup complete, %d unused for 80 days, %d didn't auth within 10 days.", expired, unauthed);
  return CMD_OK;
}
