/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: cleanupdb
 * CMDLEVEL: QCMD_DEV
 * CMDARGS: 0
 * CMDDESC: Clean up database.
 * CMDFUNC: csu_docleanupdb
 * CMDPROTO: int csu_docleanupdb(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: cleanupdb
 * CMDHELP: Cleans up inactive accounts, unused accounts and inactive channels.
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_docleanupdb(void *source, int cargc, char **cargv) {
  nick *np = (nick *)source;

  cs_cleanupdb(np);
  return CMD_OK;
}
