/* Automatically generated by mkcommandlist.pl, do not edit. */

#include "../chanserv.h"

/* Prototypes */
int csu_dodeluser(void *source, int cargc, char **cargv);
int csu_doinfo(void *source, int cargc, char **cargv);
int csu_dolanguage(void *source, int cargc, char **cargv);
int csu_dolistflags(void *source, int cargc, char **cargv);
int csu_dospewdb(void *source, int cargc, char **cargv);
int csu_dospewemail(void *source, int cargc, char **cargv);
int csu_dospewpass(void *source, int cargc, char **cargv);
int csu_dosuspenduser(void *source, int cargc, char **cargv);
int csu_dosuspenduserlist(void *source, int cargc, char **cargv);
int csu_dounsuspenduser(void *source, int cargc, char **cargv);
int csu_dousercomment(void *source, int cargc, char **cargv);
int csu_douserflags(void *source, int cargc, char **cargv);
int csu_dowhois(void *source, int cargc, char **cargv);

void _init() {
  chanservaddcommand("deluser", QCMD_OPER, 2, csu_dodeluser, "Removes a user from the bot.");
  chanservaddcommand("info", QCMD_AUTHED, 2, csu_doinfo, "Shows or changes info line.");
  chanservaddcommand("language", QCMD_AUTHED, 1, csu_dolanguage, "Shows or changes your current language.");
  chanservaddcommand("listflags", QCMD_OPER, 1, csu_dolistflags, "List users with the specified user flags.");
  chanservaddcommand("spewdb", QCMD_OPER, 1, csu_dospewdb, "Search for a user in the database.");
  chanservaddcommand("spewemail", QCMD_OPER, 1, csu_dospewemail, "Search for an e-mail in the database.");
  chanservaddcommand("spewpass", QCMD_OPER, 1, csu_dospewpass, "Search for a password in the database.");
  chanservaddcommand("suspenduser", QCMD_OPER, 1, csu_dosuspenduser, "Suspend/Delay GLINE/Instantly GLINE a user.");
  chanservaddcommand("suspenduserlist", QCMD_HELPER, 1, csu_dosuspenduserlist, "Lists suspended/locked users.");
  chanservaddcommand("unsuspenduser", QCMD_OPER, 1, csu_dounsuspenduser, "Unsuspend a user.");
  chanservaddcommand("usercomment", QCMD_OPER, 2, csu_dousercomment, "Shows or changes staff comment for a user.");
  chanservaddcommand("userflags", QCMD_AUTHED, 2, csu_douserflags, "Shows or changes user flags.");
  chanservaddcommand("whois", QCMD_AUTHED, 1, csu_dowhois, "Displays information about a user.");
}

void _fini() {
  chanservremovecommand("deluser", csu_dodeluser);
  chanservremovecommand("info", csu_doinfo);
  chanservremovecommand("language", csu_dolanguage);
  chanservremovecommand("listflags", csu_dolistflags);
  chanservremovecommand("spewdb", csu_dospewdb);
  chanservremovecommand("spewemail", csu_dospewemail);
  chanservremovecommand("spewpass", csu_dospewpass);
  chanservremovecommand("suspenduser", csu_dosuspenduser);
  chanservremovecommand("suspenduserlist", csu_dosuspenduserlist);
  chanservremovecommand("unsuspenduser", csu_dounsuspenduser);
  chanservremovecommand("usercomment", csu_dousercomment);
  chanservremovecommand("userflags", csu_douserflags);
  chanservremovecommand("whois", csu_dowhois);
}
