/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: deluser
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 2
 * CMDDESC: Removes a user from the bot.
 * CMDFUNC: csu_dodeluser
 * CMDPROTO: int csu_dodeluser(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_dodeluser(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup=getreguserfromnick(sender), *target;

  if (!rup)
    return CMD_ERROR;
  
  if (cargc<1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "deluser");
    return CMD_ERROR;
  }

  if (!(target=findreguser(sender, cargv[0])))
    return CMD_ERROR;
  
  cs_log(sender,"DELUSER %s (%s)",target->username,cargc>1?cargv[1]:"");
  cs_removeuser(target);

  chanservstdmessage(sender, QM_DONE);

  return CMD_OK;
}
