/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: lastreg
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 1
 * CMDDESC: List last N registered accounts
 * CMDFUNC: csa_dolastreg
 * CMDPROTO: int csa_dolastreg(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: lastreg [N]
 * CMDHELP: Shows list of most recently registered accounts
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"

#include <stdio.h>
#include <string.h>

int csa_dolastreg(void *source, int cargc, char **cargv) {
  reguser *rup;
  reguser *r;
  nick *sender=source;
  char *endptr;
  char tbuf[TIMELEN];
  char tbuf2[TIMELEN];
  char *suspended;
  unsigned int limit=10;
  unsigned int userID=lastuserID;
  int count=0;

  if (!(rup=getreguserfromnick(sender)))
    return CMD_ERROR;
  if (cargc > 0) {
    limit=strtol(cargv[0], &endptr, 10);
    if ((cargv[0] == endptr) || (*endptr != '\0')) {
      limit=10;
      chanservsendmessage(sender, "Value '%s' is not valid. Using default: %u", cargv[0], limit);
    }
    else if (limit > MAX_LASTREG) {
      limit=MAX_LASTREG;
      chanservsendmessage(sender, "Value '%s' is too high. Using maximum: %u.", cargv[0], MAX_LASTREG);
    }
  }

  chanservsendmessage(sender, "%-9s %-19s %-18s %-10s %-19s %s", "ID:", "Created TS:", "Username:", "Suspended:", "Last auth TS:", "last user@host");
  while (count < limit) {
    r=findreguserbyID(userID);
    if (!r) {
      if (userID == 0)
        break;
      userID--;
      continue;
    }
    q9strftime(tbuf, sizeof(tbuf), r->created);
    if (r->lastauth > 0)
      q9strftime(tbuf2, sizeof(tbuf2), r->lastauth);
    else
      strcpy(tbuf2, "-");
    suspended = (r->suspendtime > 0) ? "Suspended" : "";
    chanservsendmessage(sender, "%-9u %-19s %-18s %-10s %-19s %s", userID, tbuf, r->username, suspended, tbuf2, r->lastuserhost->content);
    count++;
    if (userID == 0)
      break;
    userID--;
  }
  chanservstdmessage(sender, QM_ENDOFLIST);
  return CMD_OK;
}
