/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: rollbackaccount
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 2
 * CMDDESC: Roll back password/email changes on an account.
 * CMDFUNC: csa_dorollbackaccount
 * CMDPROTO: int csa_dorollbackaccount(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csa_dorollbackaccount(void *source, int cargc, char **cargv) {
  reguser *rup, *trup;
  nick *sender=source;
  time_t starttime=getnettime();
  long duration;
  
  if (!(rup=getreguserfromnick(sender)))
    return CMD_ERROR;
  
  if (cargc < 2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "rollbackaccount");
    return CMD_ERROR;
  }
  
  if (!(trup=findreguser(sender, cargv[0])))
    return CMD_ERROR;
  
  if (UHasOperPriv(trup)) {
    chanservstdmessage(sender, QM_NOACCESS, "rollbackaccount", cargv[0]);
    return CMD_ERROR;
  }
  
  if (!(duration=durationtolong(cargv[1]))) {
    chanservsendmessage(sender, "Invalid duration.");
    return CMD_ERROR;
  }
  starttime-=duration;
  
  cs_log(sender,"ROLLBACKACCOUNT %s #%s %s", trup->username, rup->username, cargv[1]);
  
  csdb_rollbackaccounthistory(sender, trup, starttime);
  
  return CMD_OK;
}
