/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: spewemail
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 1
 * CMDDESC: Search for an e-mail in the database.
 * CMDFUNC: csu_dospewemail
 * CMDPROTO: int csu_dospewemail(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: spewdb <pattern>
 * CMDHELP: Displays all users with email addresses that match the supplied pattern.
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_dospewemail(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup=getreguserfromnick(sender);
  reguser *dbrup;
  int i;
  unsigned int count=0;
  
  if (!rup)
    return CMD_ERROR;
  
  if (cargc < 1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "spewemail");
    return CMD_ERROR;
  }
  
  chanservstdmessage(sender, QM_SPEWHEADER);
  for (i=0;i<REGUSERHASHSIZE;i++) {
    for (dbrup=regusernicktable[i]; dbrup; dbrup=dbrup->nextbyname) {
      if (!dbrup->email)
        continue;
      if (!match(cargv[0], dbrup->email->content)) {
        chanservsendmessage(sender, "%-15s %-10s %-30s %s", dbrup->username, UHasSuspension(dbrup)?"yes":"no", dbrup->email?dbrup->email->content:"none set", dbrup->lastuserhost?dbrup->lastuserhost->content:"none");
        count++;
        if (count >= 2000) {
          chanservstdmessage(sender, QM_TOOMANYRESULTS, 2000, "users");
          return CMD_ERROR;
        }
      }
    }
  }
  chanservstdmessage(sender, QM_RESULTCOUNT, count, "user", (count==1)?"":"s");
  
  return CMD_OK;
}
