/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: spewdb
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 1
 * CMDDESC: Search for a user in the database.
 * CMDFUNC: csu_dospewdb
 * CMDPROTO: int csu_dospewdb(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: spewdb <pattern>
 * CMDHELP: Displays all users with usernames that match the specified pattern.
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_dospewdb(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup=getreguserfromnick(sender);
  reguser *dbrup;
  int i;
  unsigned int count=0;
  char timebuf[30];
  struct tm *tmp;
  char *la;
  
  if (!rup)
    return CMD_ERROR;
  
  if (cargc < 1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "spewdb");
    return CMD_ERROR;
  }
  
  chanservstdmessage(sender, QM_SPEWHEADER);
  for (i=0;i<REGUSERHASHSIZE;i++) {
    for (dbrup=regusernicktable[i]; dbrup; dbrup=dbrup->nextbyname) {
      if ((!match(cargv[0], dbrup->username)) ||
          (dbrup->email && !match(cargv[0], dbrup->email->content)) ||
          (dbrup->lastuserhost && !match(cargv[0], dbrup->lastuserhost->content)) ||
          (dbrup->suspendreason && !match(cargv[0], dbrup->suspendreason->content))) {
        if (dbrup->lastauth) {
          tmp=gmtime(&(dbrup->lastauth));
          strftime(timebuf,15,"%d/%m/%y %H:%M",tmp);
          la=timebuf;
        } else {
          la="(never)";
        }
        
        chanservsendmessage(sender, "%-15s %-10s %-30s %-15s %s", dbrup->username, UHasSuspension(dbrup)?"yes":"no", dbrup->email?dbrup->email->content:"none set", la, dbrup->lastuserhost?dbrup->lastuserhost->content:"none");
        count++;
        if (count >= 2000) {
          chanservstdmessage(sender, QM_TOOMANYRESULTS, 2000, "users");
          return CMD_ERROR;
        }
      }
    }
  }
  chanservstdmessage(sender, QM_RESULTCOUNT, count, "user", (count==1)?"":"s");
  
  return CMD_OK;
}
