/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: suspenduserlist
 * CMDLEVEL: QCMD_HELPER
 * CMDARGS: 1
 * CMDDESC: Lists suspended/locked users.
 * CMDFUNC: csu_dosuspenduserlist
 * CMDPROTO: int csu_dosuspenduserlist(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: suspenduserlist <username or pattern>
 * CMDHELP: Displays all suspend users with usernames matching the specified pattern,
 * CMDHELP: or the single user with the specified username.
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_dosuspenduserlist(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup=getreguserfromnick(sender);
  reguser *dbrup, *trup;
  int i;
  unsigned int count=0;
  struct tm *tmp;
  char buf[200], buf2[200];
  time_t now=time(NULL);
  
  if (!rup)
    return CMD_ERROR;
  
  if (cargc < 1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "suspenduserlist");
    return CMD_ERROR;
  }
  
  chanservstdmessage(sender, QM_SUSPENDUSERLISTHEADER);
  for (i=0;i<REGUSERHASHSIZE;i++) {
    for (dbrup=regusernicktable[i]; dbrup; dbrup=dbrup->nextbyname) {
      if (!UHasSuspension(dbrup))
        continue;
      
      if (!match(cargv[0], dbrup->username)) {
        char suspendtype[100];
        char *bywhom=0;
        
        if ((UIsGline(dbrup) || UIsDelayedGline(dbrup)) && !UHasOperPriv(rup))
          continue;
        
        if (UIsDelayedGline(dbrup))
          strcpy(suspendtype, "delayed gline");
        else if (UIsGline(dbrup))
          strcpy(suspendtype, "instant gline");
        else if (UIsSuspended(dbrup))
          strcpy(suspendtype, "suspended");
        else
          strcpy(suspendtype, "not used");
        
        trup=findreguserbyID(dbrup->suspendby);
        if (trup)
          bywhom=trup->username;
        else
          bywhom="(unknown)";
        
        if (dbrup->suspendexp) {
          tmp=gmtime(&(dbrup->suspendexp));
          strftime(buf,15,"%d/%m/%y %H:%M",tmp);
        }
        
        tmp=gmtime(&(dbrup->suspendtime));
        strftime(buf2,15,"%d/%m/%y %H:%M",tmp);

        count++;
        chanservsendmessage(sender, "%-15s %-13s %-15s %-15s %-15s %s", dbrup->username, suspendtype, UHasOperPriv(rup)?bywhom:"not shown", buf2, (dbrup->suspendexp)?((now >= dbrup->suspendexp)?"next auth":buf):"never", dbrup->suspendreason?dbrup->suspendreason->content:"(none)");
        if (count >= 2000) {
          chanservstdmessage(sender, QM_TOOMANYRESULTS, 2000, "users");
          return CMD_ERROR;
        }
      }
    }
  }
  chanservstdmessage(sender, QM_RESULTCOUNT, count, "user", (count==1)?"":"s");
  
  return CMD_OK;
}
