/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: whoami
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 0
 * CMDDESC: Displays information about you
 * CMDFUNC: csu_dowhoami
 * CMDPROTO: int csu_dowhoami(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_dowhois(void *, int, char **);

int csu_dowhoami(void *source, int cargc, char **cargv) {
  nick *sender=source;
  cargv[0] = sender->nick;
  return csu_dowhois(source, 1, cargv);
}
