/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: whois
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 1
 * CMDDESC: Displays information about a user.
 * CMDFUNC: csu_dowhois
 * CMDPROTO: int csu_dowhois(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csu_dowhois(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup=getreguserfromnick(sender), *target;
  char buf[200];
  char nbpos=0;
  nicklist *nlp;
  struct tm *tmp;
  regchanuser *rcup, *rcup2;
  flag_t flagmask, flags;
  int doneheader=0;

  if (!(rup=getreguserfromnick(sender)))
    return CMD_ERROR;
  
  if (cargc<1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "whois");
    return CMD_ERROR;
  }
  
  if (!(target=findreguser(sender, cargv[0]))) {
    nick* np;
    
    if (cs_privcheck(QPRIV_VIEWFULLWHOIS, sender) && (np=getnickbynick(cargv[0]))) {
      activeuser* aup=getactiveuserfromnick(np);
      chanservsendmessage(sender, "%s has attempted to auth %d time%s.", np->nick, aup->authattempts, 
        aup->authattempts==1?"":"s");
    }
    return CMD_ERROR;
  }

  if (cargv[0][0]=='#') {
    chanservstdmessage(sender, QM_WHOISHEADER_AUTH, target->username);
  } else {
    chanservstdmessage(sender, QM_WHOISHEADER_NICK, cargv[0], target->username);
  }

  if (rup==target || cs_privcheck(QPRIV_VIEWFULLWHOIS, sender)) {
    chanservstdmessage(sender, QM_WHOIS_USERID, target->ID);
  }

  if (cs_privcheck(QPRIV_VIEWUSERFLAGS, sender)) {
    flagmask=QUFLAG_ALL;
  } else {  
    if (UIsAdmin(target))
      chanservstdmessage(sender, QM_USERISADMIN, target->username);
    else if (UIsOper(target))
      chanservstdmessage(sender, QM_USERISOPER, target->username);
    else if (UIsHelper(target))
      chanservstdmessage(sender, QM_USERISHELPER, target->username);
    
    if (UIsDev(target))
      chanservstdmessage(sender, QM_USERISDEV, target->username);

    flagmask=0;
  }

  if (rup==target)
    flagmask|=(QUFLAG_OPER | QUFLAG_DEV | QUFLAG_HELPER | 
	       QUFLAG_ADMIN | QUFLAG_INFO | QUFLAG_NOTICE);

  if (flagmask & target->flags)
    chanservstdmessage(sender, QM_WHOIS_FLAGS, printflags(flagmask & target->flags, ruflags));

  if (!target->nicks) {
    chanservstdmessage(sender, QM_WHOIS_USERS, "(none)");
  } else {
    for (nlp=target->nicks; ;nlp=nlp->next) {
      if (nbpos>0 && (!nlp || nbpos+strlen(nlp->np->nick) > 60)) {
	chanservstdmessage(sender, QM_WHOIS_USERS, buf);
	nbpos=0;
      }

      if (!nlp)
	break;

      nbpos+=sprintf(buf+nbpos,"%s ",nlp->np->nick);
    }
  }

  if (target->created) {
    tmp=gmtime(&(target->created));
    strftime(buf,15,"%d/%m/%y %H:%M",tmp);
    
    chanservstdmessage(sender, QM_WHOIS_CREATED, buf);
  }

  tmp=gmtime(&(target->lastauth));
  strftime(buf,15,"%d/%m/%y %H:%M",tmp);

  chanservstdmessage(sender, QM_WHOIS_LASTAUTH, buf);
  
  if (target->lastuserhost && (rup==target || cs_privcheck(QPRIV_VIEWFULLWHOIS, sender))) {
    chanservstdmessage(sender, QM_WHOIS_USERLANG, cslanguages[target->languageid] ?
		       cslanguages[target->languageid]->name->content : "(unknown)");
    chanservstdmessage(sender, QM_WHOIS_LASTUSERHOST, target->lastuserhost->content);
  }

  if (target->email && (rup==target || cs_privcheck(QPRIV_VIEWEMAIL, sender))) {
    chanservstdmessage(sender, QM_WHOIS_EMAIL, target->email->content);

    tmp=gmtime(&(target->lastemailchange));
    strftime(buf,15,"%d/%m/%y %H:%M",tmp);
    
    chanservstdmessage(sender, QM_WHOIS_EMAILSET, buf);    
  }

  if (target->info) {
    chanservstdmessage(sender, QM_WHOIS_INFO, target->info->content);
  }

  if (target->comment && (cs_privcheck(QPRIV_VIEWCOMMENTS, sender))) {
    chanservstdmessage(sender, QM_WHOIS_COMMENT, target->comment->content);
  }
  
  for (rcup=target->knownon;rcup;rcup=rcup->nextbyuser) {
    if (!UHasHelperPriv(rup)) {
      if (!(rcup2=findreguseronchannel(rcup->chan,rup)))
	continue;
      
      if (!CUHasVoicePriv(rcup2))
	continue;
      
      flagmask = (QCUFLAG_OWNER | QCUFLAG_MASTER | QCUFLAG_OP | QCUFLAG_VOICE | QCUFLAG_AUTOVOICE | 
		  QCUFLAG_AUTOOP | QCUFLAG_TOPIC);
      
      if (CUHasMasterPriv(rcup2))
	flagmask |= (QCUFLAG_DENY | QCUFLAG_QUIET | QCUFLAG_BANNED);
    } else {
      flagmask=QCUFLAG_ALL;
    }

    if (!(flags=rcup->flags & flagmask)) 
      continue;

    if (!doneheader) {
      doneheader=1;
      chanservstdmessage(sender, QM_WHOIS_CHANHEADER, target->username);
    }

    chanservsendmessage(sender, " %-30s %s",rcup->chan->index->name->content,printflags(flags, rcuflags));
  }

  chanservstdmessage(sender, QM_ENDOFLIST);

  return CMD_OK;
}
