/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: chanstat
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 1
 * CMDDESC: Displays channel activity statistics.
 * CMDFUNC: csc_dochanstat
 * CMDPROTO: int csc_dochanstat(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../nick/nick.h"
#include "../../lib/flags.h"
#include "../../lib/irc_string.h"
#include "../../channel/channel.h"
#include "../../parser/parser.h"
#include "../../irc/irc.h"
#include "../../localuser/localuserchannel.h"
#include <string.h>
#include <stdio.h>

int csc_dochanstat(void *source, int cargc, char **cargv) {
  nick *sender=source;
  chanindex *cip;
  regchan *rcp;
  char timebuf[30];
  
  if (cargc<1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "chanstat");
    return CMD_ERROR;
  }

  if (!(cip=cs_checkaccess(sender, cargv[0], CA_MASTERPRIV,
			   NULL, "chanstat", QPRIV_VIEWFULLCHANLEV, 0)))
    return CMD_ERROR;
  
  rcp=cip->exts[chanservext];

  chanservstdmessage(sender, QM_STATSHEADER, cip->name->content);

  strftime(timebuf, 30, "%d/%m/%y %H:%M", localtime(&(rcp->created)));
  chanservstdmessage(sender, QM_STATSADDED, timebuf);

  /* Show opers founder/addedby/type info */
  if (cs_privcheck(QPRIV_VIEWFULLCHANLEV, sender)) {
    reguser *founder=NULL, *addedby=NULL;

    strftime(timebuf, 30, "%d/%m/%y %H:%M", localtime(&(rcp->lastactive)));
    chanservstdmessage(sender, QM_STATSLASTACTIVE, timebuf);


    addedby=findreguserbyID(rcp->addedby);
    chanservstdmessage(sender, QM_ADDEDBY, addedby ? addedby->username : "(unknown)");
    founder=findreguserbyID(rcp->founder);
    chanservstdmessage(sender, QM_FOUNDER, founder ? founder->username : "(unknown)");      
    chanservstdmessage(sender, QM_CHANTYPE, chantypes[rcp->chantype]->content);
  }

  strftime(timebuf, 30, "%d/%m/%y %H:%M", localtime(&(rcp->created)));

  chanservstdmessage(sender, QM_STATSJOINS, timebuf, rcp->maxusers, rcp->totaljoins, 
		     (float)rcp->totaljoins/ ((time(NULL)-rcp->created)/(3600*24)));

  strftime(timebuf, 30, "%d/%m/%y %H:%M", localtime(&(rcp->statsreset)));

  chanservstdmessage(sender, QM_STATSJOINS, timebuf, rcp->tripusers, rcp->tripjoins, 
		     (float)rcp->tripjoins / ((time(NULL)-rcp->statsreset)/(3600*24)));

  return CMD_OK;
}
