/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: chanlevhistory
 * CMDLEVEL: QCMD_HELPER
 * CMDARGS: 2
 * CMDDESC: View user access changes on a channel.
 * CMDFUNC: csc_dochanlevhistory
 * CMDPROTO: int csc_dochanlevhistory(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../nick/nick.h"
#include "../../lib/flags.h"
#include "../../lib/irc_string.h"
#include "../../channel/channel.h"
#include "../../parser/parser.h"
#include "../../irc/irc.h"
#include "../../localuser/localuserchannel.h"
#include <string.h>
#include <stdio.h>

int csc_dochanlevhistory(void *source, int cargc, char **cargv) {
  nick *sender=source;
  chanindex *cip;
  reguser *rup;
  regchan *rcp;
  time_t starttime=getnettime();
  
  if (cargc < 1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "chanlevhistory");
    return CMD_ERROR;
  }
  
  if (!(cip=cs_checkaccess(sender, cargv[0], 0, NULL, NULL, 0, 0)))
    return CMD_ERROR;
  
  rcp=(regchan*)cip->exts[chanservext];
  
  if (cargc > 1)
    starttime-=durationtolong(cargv[1]);
  else
    starttime-=3600;
  
  csdb_retreivechanlevhistory(sender, rcp, starttime);
  
  return CMD_OK;
}
