/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: permban
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 3
 * CMDDESC: Permanently bans a hostmask on a channel.
 * CMDFUNC: csc_dopermban
 * CMDPROTO: int csc_dopermban(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../nick/nick.h"
#include "../../lib/flags.h"
#include "../../lib/irc_string.h"
#include "../../channel/channel.h"
#include "../../parser/parser.h"
#include "../../irc/irc.h"
#include "../../localuser/localuserchannel.h"
#include <string.h>
#include <stdio.h>

int csc_dopermban(void *source, int cargc, char **cargv) {
  nick *sender=source;
  chanindex *cip;
  regban *rbp;
  regchan *rcp;
  reguser *rup=getreguserfromnick(sender);

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "permban");
    return CMD_ERROR;
  }

  if (!(cip=cs_checkaccess(sender, cargv[0], CA_MASTERPRIV, NULL, "permban",0, 0)))
    return CMD_ERROR;

  rcp=cip->exts[chanservext];

  rbp=getregban();
  rbp->ID=++lastbanID;
  rbp->cbp=makeban(cargv[1]);
  rbp->setby=rup->ID;
  rbp->expiry=0;
  if (cargc>2)
    rbp->reason=getsstring(cargv[2],200);
  else
    rbp->reason=NULL;
  rbp->next=rcp->bans;
  rcp->bans=rbp;

  cs_setregban(cip, rbp);
  csdb_createban(rcp, rbp);
  
  chanservstdmessage(sender, QM_DONE);
  return CMD_OK;
}
