/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: permban
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 3
 * CMDDESC: Permanently bans a hostmask on a channel.
 * CMDFUNC: csc_dopermban
 * CMDPROTO: int csc_dopermban(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: PERMBAN <channel> <hostmask> [<reason>]
 * CMDHELP: Permanently bans the provided hostmask on the channel.  If the ban is
 * CMDHELP: removed from the channel e.g. by a channel op or the BANTIMER feature, the
 * CMDHELP: ban will be reapplied if a matching user joins the channel.  Bans
 * CMDHELP: set with the PERMBAN command can be removed via BANCLEAR or BANDEL.  Any users
 * CMDHELP: matching the hostmask will be kicked from the channel.
 * CMDHELP: Where:
 * CMDHELP: channel  - channel to set a ban on
 * CMDHELP: hostmask - hastmask (nick!user@host) to ban.
 * CMDHELP: reason   - reason for the ban.  This will be used in kick messages when kicking
 * CMDHELP:            users matching the ban.  If this is not provided the generic message
 * CMDHELP:            \"Banned.\" will be used.
 * CMDHELP: PERMBAN requires master (+m) access on the named channel.
 */

#include "../chanserv.h"
#include "../../nick/nick.h"
#include "../../lib/flags.h"
#include "../../lib/irc_string.h"
#include "../../channel/channel.h"
#include "../../parser/parser.h"
#include "../../irc/irc.h"
#include "../../localuser/localuserchannel.h"
#include <string.h>
#include <stdio.h>

int csc_dopermban(void *source, int cargc, char **cargv) {
  nick *sender=source;
  chanindex *cip;
  regban *rbp;
  regchan *rcp;
  reguser *rup=getreguserfromnick(sender);

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "permban");
    return CMD_ERROR;
  }

  if (!(cip=cs_checkaccess(sender, cargv[0], CA_MASTERPRIV, NULL, "permban",0, 0)))
    return CMD_ERROR;

  rcp=cip->exts[chanservext];

  rbp=getregban();
  rbp->ID=++lastbanID;
  rbp->cbp=makeban(cargv[1]);
  rbp->setby=rup->ID;
  rbp->expiry=0;
  if (cargc>2)
    rbp->reason=getsstring(cargv[2],200);
  else
    rbp->reason=NULL;
  rbp->next=rcp->bans;
  rcp->bans=rbp;

  cs_setregban(cip, rbp);
  csdb_createban(rcp, rbp);
  
  chanservstdmessage(sender, QM_DONE);
  return CMD_OK;
}
