/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: snails
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 3
 * CMDDESC: Sets the snails on an unsuspecting target.
 * CMDFUNC: csc_dosnails
 * CMDPROTO: int csc_dosnails(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: SNAILS <channel> <nickname>
 * CMDHELP: Sends a legion of snails to attack the supplied nickname in the supplied channel.
 */

#include "../chanserv.h"

int csc_dosnails(void *source, int cargc, char **cargv) {
  nick *sender = (nick *)source;
  reguser *rup=getreguserfromnick(sender);
  chanindex *cip;
  char *cc, *cn;
  int giant = 0;

  if (!rup)
    return CMD_ERROR;

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "snails");
    return CMD_ERROR;
  }
  if(cargc == 2) {
    cc = cargv[0];
    cn = cargv[1];
  } else { /* be careful adding more args! */
    if(!strcmp(cargv[0], "-gggGIANT")) /* please don't leak me! :( else I'll have to write more code and put it in the config file */
      giant = 1;

    cc = cargv[1];
    cn = cargv[2];
  }

  if (!(cip=findchanindex(cc)) || !cip->channel) {
    chanservstdmessage(sender, QM_UNKNOWNCHAN, cc);
    return CMD_ERROR;
  }

  if(!giant) {
    sendmessagetochannel(chanservnick, cip->channel, "\001ACTION sets the snails on %s _@\" _@\" _@\"\001", cn);
  } else {
    sendmessagetochannel(chanservnick, cip->channel, "\001ACTION sets the GIANT snails on %s:\001", cn);
    sendmessagetochannel(chanservnick, cip->channel, "       ____  _ _         ____  _ _         ____  _ _");
    sendmessagetochannel(chanservnick, cip->channel, "      / __ \\( | )       / __ \\( | )       / __ \\( | )");
    sendmessagetochannel(chanservnick, cip->channel, "     / / _` |V V       / / _` |V V       / / _` |V V");
    sendmessagetochannel(chanservnick, cip->channel, "    | | (_| |         | | (_| |         | | (_| |");
    sendmessagetochannel(chanservnick, cip->channel, " ____\\ \\__,_|      ____\\ \\__,_|      ____\\ \\__,_|");
    sendmessagetochannel(chanservnick, cip->channel, "|_____\\____/      |_____\\____/      |_____\\____/");
  }

  cs_log(sender,"SNAILS %s %s%s", cc, cn, giant?" (giant)":"");
  chanservstdmessage(sender, QM_DONE);
  return CMD_OK;
}
