/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: snails
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 2
 * CMDDESC: Sets the snails on an unsuspecting target.
 * CMDFUNC: csc_dosnails
 * CMDPROTO: int csc_dosnails(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: SNAILS <channel> <nickname>
 * CMDHELP: Sends a legion of snails to attack the supplied nickname in the supplied channel.
 */

#include "../chanserv.h"

int csc_dosnails(void *source, int cargc, char **cargv) {
  nick *sender = (nick *)source;
  reguser *rup=getreguserfromnick(sender);
  chanindex *cip;

  if (!rup)
    return CMD_ERROR;

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "snails");
    return CMD_ERROR;
  }

  if (!(cip=findchanindex(cargv[0])) || !cip->channel) {
    chanservstdmessage(sender, QM_UNKNOWNCHAN, cargv[0]);
    return CMD_ERROR;
  }

  sendmessagetochannel(chanservnick, cip->channel, "\001ACTION sets the snails on %s _@\" _@\" _@\"", cargv[1]);

  chanservstdmessage(sender, QM_DONE);
  return CMD_OK;
}
