/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: tempban
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 4
 * CMDDESC: Bans a hostmask on a channel for a specified time period.
 * CMDFUNC: csc_dotempban
 * CMDPROTO: int csc_dotempban(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../nick/nick.h"
#include "../../lib/flags.h"
#include "../../lib/irc_string.h"
#include "../../channel/channel.h"
#include "../../parser/parser.h"
#include "../../irc/irc.h"
#include "../../localuser/localuserchannel.h"
#include <string.h>
#include <stdio.h>

int csc_dotempban(void *source, int cargc, char **cargv) {
  nick *sender=source;
  chanindex *cip;
  regban *rbp;
  regchan *rcp;
  reguser *rup=getreguserfromnick(sender);
  unsigned int duration;

  if (cargc<3) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "tempban");
    return CMD_ERROR;
  }

  if (!(cip=cs_checkaccess(sender, cargv[0], CA_MASTERPRIV, NULL, "tempban",0, 0)))
    return CMD_ERROR;

  rcp=cip->exts[chanservext];

  duration=durationtolong(cargv[2]);
  if (duration > 400000000) {
    chanservstdmessage(sender, QM_DURATIONTOOLONG, cargv[2]);
    return CMD_ERROR;
  }
  
  rbp=getregban();
  rbp->ID=++lastbanID;
  rbp->cbp=makeban(cargv[1]);
  rbp->setby=rup->ID;
  rbp->expiry=time(NULL)+duration;
  if (cargc>3)
    rbp->reason=getsstring(cargv[3],200);
  else
    rbp->reason=NULL;
  rbp->next=rcp->bans;
  rcp->bans=rbp;

  cs_setregban(cip, rbp);
  csdb_createban(rcp, rbp);
  
  chanservstdmessage(sender, QM_DONE);
  return CMD_OK;
}
