/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: unsuspendchan
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 1
 * CMDDESC: Unsuspends a channel from the bot.
 * CMDFUNC: csc_dounsuspendchan
 * CMDPROTO: int csc_dounsuspendchan(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../../nick/nick.h"
#include "../../lib/flags.h"
#include "../../lib/irc_string.h"
#include "../../channel/channel.h"
#include "../../parser/parser.h"
#include "../../irc/irc.h"
#include "../../localuser/localuserchannel.h"
#include <string.h>
#include <stdio.h>

int csc_dounsuspendchan(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup=getreguserfromnick(sender);
  chanindex *cip;
  regchan *rcp;

  if (!rup)
    return CMD_ERROR;

  if (cargc<1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "unsuspendchan");
    return CMD_ERROR;
  }

  if (!(cip=findchanindex(cargv[0])) || !(rcp=cip->exts[chanservext])) {
    chanservstdmessage(sender, QM_UNKNOWNCHAN, cargv[0]);
    return CMD_ERROR;
  }

  if(!CIsSuspended(rcp)) {
    chanservstdmessage(sender, QM_CHANNELNOTSUSPENDED, cip->name->content);
    cs_log(sender,"UNSUSPENDCHAN %s is not suspended",cip->name->content);
    return CMD_ERROR;
  }

  CClearSuspended(rcp);
  cs_log(sender,"UNSUSPENDCHAN %s (%s)",cip->name->content,rcp->suspendreason->content);
  freesstring(rcp->suspendreason);
  rcp->suspendreason = NULL;
  rcp->suspendby = 0;

  if(cip->channel)
    chanservjoinchan(cip->channel);

  csdb_updatechannel(rcp);
  chanservstdmessage(sender, QM_DONE);

  return CMD_OK;
}
