include ../build.mk

.PHONY: all

default: all

all: sstring.o array.o splitline.o base64.o flags.o irc_string.o strlfunc.o sha1.o irc_ipv6.o rijndael.o sha2.o hmac.o prng.o md5.o stringbuf.o cbc.o curve25519-donna.o curve25519.o
