include ../build.mk

.PHONY: all

TARGETS=huser.o hhooks.o hconf.o hgen.o hchannel.o hban.o hchanban.o hlamer.o htopic.o hstat.o hqueue.o hterm.o hcensor.o haccount.o hdef.o hcommand.o hcommands.o helpmod2.o helpmod_entries.o helpmod_alias.o hticket.o hed.o

all: helpmod2.so

helpmod2.so: $(TARGETS)
