/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: challengeauth
 * CMDLEVEL: QCMD_ALIAS | QCMD_SECURE | QCMD_NOTAUTHED
 * CMDARGS: 3
 * CMDDESC: Authenticates you on the bot using challenge response.
 * CMDFUNC: csa_dochallengeauth
 * CMDPROTO: int csa_dochallengeauth(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include <time.h>

int csa_auth(void *source, int cargc, char **cargv, CRAlgorithm alg);

int csa_dochallengeauth(void *source, int cargc, char **cargv) {
  CRAlgorithm alg;
  activeuser* aup;
  time_t t;
  nick *sender=(nick *)source;

  if(cargc<3) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "challengeauth");
    return CMD_ERROR;
  }

  if (!(aup=getactiveuserfromnick(sender)))
    return CMD_ERROR;

  t = time(NULL);
  if(t > aup->entropyttl) {
    chanservstdmessage(sender, QM_NOCHALLENGE);
    return CMD_ERROR;
  }

  aup->entropyttl = 0;

  alg = cs_cralgorithm(cargv[2]);
  if(!alg) {
    chanservstdmessage(sender, QM_CHALLENGEBADALGORITHM);
    return CMD_ERROR;
  }

  return csa_auth(sender, cargc, cargv, alg);
}
