/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: checkhashpass
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 3
 * CMDDESC: Checks supplied password against a version hashed in the database.
 * CMDFUNC: csa_docheckhashpass
 * CMDPROTO: int csa_docheckhashpass(void *source, int cargc, char **cargv);
 * CMDHELP: Used by external services for password verficiation.
 */

#include "../chanserv.h"

int csa_docheckhashpass(void *source, int cargc, char **cargv) {
  nick *sender=(nick *)source;
  reguser *rup;  
  char *flags;

  if(cargc<3) {
    chanservsendmessage(sender, "CHECKHASHPASS FAIL args");
/*    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "checkhashpass");*/
    return CMD_ERROR;
  }

  if (!(rup=findreguserbynick(cargv[0]))) {
    chanservsendmessage(sender, "CHECKHASHPASS FAIL user");
    return CMD_OK;
  }

  flags = printflags(QUFLAG_ALL & rup->flags, ruflags);
  if(UHasSuspension(rup)) {
    chanservsendmessage(sender, "CHECKHASHPASS FAIL suspended %s %s %u", rup->username, flags, rup->ID);
  } else if(!checkhashpass(rup, cargc<3?NULL:cargv[2], cargv[1])) {
    chanservsendmessage(sender, "CHECKHASHPASS FAIL digest %s %s %u", rup->username, flags, rup->ID);
  } else {
    chanservsendmessage(sender, "CHECKHASHPASS OK %s %s %u %s", rup->username, flags, rup->ID, rup->email?rup->email->content:"-");
  }

  return CMD_OK;
}
