/* Automatically generated by mkcommandlist.pl, do not edit. */

#include "../chanserv.h"

/* Prototypes */
int csa_doauth(void *source, int cargc, char **cargv);
int csa_doauthhistory(void *source, int cargc, char **cargv);
int csa_dochallenge(void *source, int cargc, char **cargv);
int csa_dochallengeauth(void *source, int cargc, char **cargv);
int csa_doemail(void *source, int cargc, char **cargv);
int csa_dogetpw(void *source, int cargc, char **cargv);
int csa_dohello(void *source, int cargc, char **cargv);
int csa_doauth(void *source, int cargc, char **cargv);
int csa_donewpw(void *source, int cargc, char **cargv);
int csa_doreqpw(void *source, int cargc, char **cargv);
int csa_doreset(void *source, int cargc, char **cargv);
int csa_dosendpw(void *source, int cargc, char **cargv);
int csa_dosetmail(void *source, int cargc, char **cargv);
int csa_dosetpw(void *source, int cargc, char **cargv);
void authcmds_init(void);
void authcmds_fini(void);


void _init() {
  authcmds_init();
  chanservaddcommand("auth", QCMD_SECURE | QCMD_NOTAUTHED, 2, csa_doauth, "Authenticates you on the bot.", "Usage: AUTH <username> <password>\nAuthenticates you on the bot, where:\nusername - your username\npassword - your password\nIf you do not have a username and password, see HELLO.\nNote: due to the sensitive nature of this command, you must send the message\nto Q@CServe.quakenet.org when using it.\nNote: the preferred way to authenticate is to use the /AUTH command.\n");
  chanservaddcommand("authhistory", QCMD_AUTHED, 1, csa_doauthhistory, "View auth history for an account.", "Usage: AUTHHISTORY\nDisplays details of the last 10 logins with your account.  Details include\nhostmask, login time, disconnect time and reason.\n");
  chanservaddcommand("challenge", QCMD_SECURE | QCMD_NOTAUTHED, 0, csa_dochallenge, "Returns a challenge for use in challengeauth.", "Usage: challenge\nSupplies you with a challenge and a list of algorithms accepted\nfor challenge response authentication, see CHALLENGEAUTH help\nfor more details.\n");
  chanservaddcommand("challengeauth", QCMD_SECURE | QCMD_NOTAUTHED, 3, csa_dochallengeauth, "Authenticates you on the bot using challenge response.", "Usage: challengeauth <username> <response> <hmac algorithm>\nAuthenticates using challenge response.\nTo generate the response from the challenge, calculate the following:\n  HMAC(challenge){k}\nwhere HMAC is the hash message authentication code as described in\nRFC 2104, k is HEXDIGEST(<lower case username>:HEXDIGEST(<password>))\nand HEXDIGEST is the hash function used in the MAC construction.\nFor example code see the website.\n");
  chanservaddcommand("email", QCMD_SECURE | QCMD_AUTHED, 3, csa_doemail, "Change your email address.", "Usage: EMAIL <password> <email> <email>\nChanges your register email address.  Confirmation of the change will be sent\nboth old and new addresses.  Where:\npassword - your password\nemail    - new email address.  Must be entered exactly the same way twice to avoid\n           mistakes.\nNote: due to the sensitive nature of this command, you must send the message \nto Q@CServe.quakenet.org when using it.\n");
  chanservaddcommand("getpassword", QCMD_OPER, 2, csa_dogetpw, "Gets a users password", "Usage: getpassword <username>\nFetches the password for the specified username.\n");
  chanservaddcommand("hello", QCMD_NOTAUTHED, 2, csa_dohello, "Creates a new user account.", "Usage: HELLO <email> <email>\nCreates a new user account for yourself.  Your current nickname will be used\nfor the name of the account, and may only contain letters, numbers and \nhyphens (-).  An email containing password details will be sent to the email\naddress supplied.  Where:\nemail    - your email address.  Must be entered the same way both times.\n");
  chanservaddcommand("login", QCMD_SECURE | QCMD_NOTAUTHED | QCMD_ALIAS, 2, csa_doauth, "Authenticates you on the bot.", "Usage: LOGIN <username> <password>\nAuthenticates you on the bot, where:\nusername - your username\npassword - your password\nIf you do not have a username and password, see HELLO.\nNote: due to the sensitive nature of this command, you must send the message\nto Q@CServe.quakenet.org when using it.\nNote: the preferred way to authenticate is to use the /AUTH command.\n");
  chanservaddcommand("newpass", QCMD_SECURE | QCMD_AUTHED, 3, csa_donewpw, "Change your password.", "Usage: NEWPASS <oldpassword> <newpassword> <newpassword>\nChanges your account password.  Your new password must be at least 6 characters\nlong, contain at least one number and one letter, and may not contain sequences\nof letters or numbers.  Your new password will be sent to your registered email\naddress.  Where:\noldpassword - your existing account password\nnewpassword - your desired new password.  Must be entered the same both times.\nNote: due to the sensitive nature of this command, you must send the message to\nQ@CServe.quakenet.org when using it.\n");
  chanservaddcommand("requestpassword", QCMD_NOTAUTHED, 1, csa_doreqpw, "Requests the current password by email.", "Usage: REQUESTPASSWORD <email>\nSends your current password to your registered email address, where:\nemail    - your registered email address\n");
  chanservaddcommand("reset", QCMD_NOTAUTHED, 2, csa_doreset, "Restores the old details on an account after a change.", "Usage: RESET <username> <code>\nRestores your old email address and password if any of these\nhave recently changed, where the following parameters are:\nusername - your username\ncode     - the code received in the RESET email.\n");
  chanservaddcommand("sendpassword", QCMD_HELPER, 1, csa_dosendpw, "Sends the users current password by email.", "Usage: SENDPASSWORD <username>\nSends the password for the specified account to the specified users email address.\n");
  chanservaddcommand("setemail", QCMD_OPER, 2, csa_dosetmail, "Set the email address.", "Usage: setemail <username> <email address>\nSets the email address for the specified username.\n");
  chanservaddcommand("setpassword", QCMD_OPER, 2, csa_dosetpw, "Set a new password.", "Usage: setpassword <username> <password>\nSets the password for the specified username.\n");
}

void _fini() {
  authcmds_fini();
  chanservremovecommand("auth", csa_doauth);
  chanservremovecommand("authhistory", csa_doauthhistory);
  chanservremovecommand("challenge", csa_dochallenge);
  chanservremovecommand("challengeauth", csa_dochallengeauth);
  chanservremovecommand("email", csa_doemail);
  chanservremovecommand("getpassword", csa_dogetpw);
  chanservremovecommand("hello", csa_dohello);
  chanservremovecommand("login", csa_doauth);
  chanservremovecommand("newpass", csa_donewpw);
  chanservremovecommand("requestpassword", csa_doreqpw);
  chanservremovecommand("reset", csa_doreset);
  chanservremovecommand("sendpassword", csa_dosendpw);
  chanservremovecommand("setemail", csa_dosetmail);
  chanservremovecommand("setpassword", csa_dosetpw);
}
