/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: email
 * CMDLEVEL: QCMD_AUTHED
 * CMDARGS: 3
 * CMDDESC: Change your email address.
 * CMDFUNC: csa_doemail
 * CMDPROTO: int csa_doemail(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../authlib.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csa_doemail(void *source, int cargc, char **cargv) {
  reguser *rup;
  nick *sender=source;
  maildomain *mdp, *smdp;
  char *local;
  char *dupemail;

  if (cargc<3) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "email");
    return CMD_ERROR;
  }

  if (!(rup=getreguserfromnick(sender)))
    return CMD_ERROR;

  if (!checkmasterpassword(rup, cargv[0])) {
    chanservstdmessage(sender, QM_AUTHFAIL);
    cs_log(sender,"EMAIL FAIL username %s bad masterpass %s",rup->username,cargv[0]);
    return CMD_ERROR;
  }

  if (strcmp(cargv[1],cargv[2])) {
    chanservstdmessage(sender, QM_EMAILDONTMATCH);
    cs_log(sender,"EMAIL FAIL username %s email don't match (%s vs %s)",rup->username,cargv[1],cargv[2]);
    return CMD_ERROR;
  }

  if (csa_checkeboy(sender, cargv[1]))
    return CMD_ERROR;

  mdp=findorcreatemaildomain(cargv[1]);
  for(smdp=mdp; smdp; smdp=smdp->parent) {
    if((smdp->count >= smdp->limit) && (smdp->limit > 0)) {
      chanservstdmessage(sender, QM_DOMAINLIMIT);
      return CMD_ERROR;
    }
  }

  csdb_createmail(rup, QMAIL_NEWEMAIL);
  csdb_accounthistory_insert(sender, NULL, NULL, rup->email, getsstring(cargv[1], EMAILLEN));
  delreguserfrommaildomain(rup,rup->domain);
  freesstring(rup->email);
  rup->email=getsstring(cargv[1],EMAILLEN);
  rup->lastemailchange=time(NULL);
  rup->domain=findorcreatemaildomain(rup->email->content);
  addregusertomaildomain(rup, rup->domain);
  dupemail = strdup(rup->email->content);
  if(local=strchr(dupemail, '@')) {
    *(local++)='\0';
    rup->localpart=getsstring(local,EMAILLEN);
  } else {
    rup->localpart=NULL;
  }
  free(dupemail);

  chanservstdmessage(sender, QM_EMAILCHANGED, cargv[1]);
  cs_log(sender,"EMAIL OK username %s",rup->username);
  csdb_updateuser(rup);

  return CMD_OK;
}
