/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: requestpassword
 * CMDALIASES: requestpass
 * CMDLEVEL: QCMD_HIDDEN
 * CMDARGS: 1
 * CMDDESC: Requests the current password by email.
 * CMDFUNC: csa_doreqpw
 * CMDPROTO: int csa_doreqpw(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: @UCOMMAND@ <email>
 * CMDHELP: Sends your current password to your registered email address, where:
 * CMDHELP: email    - your registered email address
 */

#include "../chanserv.h"
#include "../authlib.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csa_doreqpw(void *source, int cargc, char **cargv) {
  nick *sender=source;

  chanservstdmessage(sender, QM_CMDDEPRECATEDPREFER, "LOSTPASSWORD");

  return CMD_OK;
}
