/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: requestpassword
 * CMDLEVEL: QCMD_NOTAUTHED
 * CMDARGS: 2
 * CMDDESC: Requests the current password by email.
 * CMDFUNC: csa_doreqpw
 * CMDPROTO: int csa_doreqpw(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: REQUESTPASSWORD <username> <email>
 * CMDHELP: Sends your current password to your registered email address, where:
 * CMDHELP: username - your username
 * CMDHELP: email    - your registered email address
 */

#include "../chanserv.h"
#include "../authlib.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csa_doreqpw(void *source, int cargc, char **cargv) {
  reguser *rup;
  nick *sender=source;

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "requestpassword");
    return CMD_ERROR;
  }

  if (!(rup=findreguser(sender, cargv[0])))
    return CMD_ERROR;

  if (strcasecmp(cargv[1],rup->email->content)) {
    chanservstdmessage(sender, QM_BADEMAIL, rup->username);
    cs_log(sender,"REQUESTPASSWORD FAIL wrong email, username %s email %s",rup->username,cargv[1]);
    return CMD_ERROR;
  }

  if (csa_checkthrottled(sender, rup, "REQUESTPASSWORD"))
    return CMD_ERROR;

  rup->lastemailchange=time(NULL);
  csdb_updateuser(rup);

  if(rup->lastauth) {
    csdb_createmail(rup, QMAIL_REQPW);
  } else {
    csdb_createmail(rup, QMAIL_NEWACCOUNT); /* user hasn't authed yet and needs to do the captcha */
  }
  chanservstdmessage(sender, QM_MAILQUEUED, rup->username);
  cs_log(sender,"REQUESTPASSWORD OK username %s email %s", rup->username,rup->email->content);

  return CMD_OK;
}
