/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: setpassword
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 2
 * CMDDESC: Set a new password.
 * CMDFUNC: csa_dosetpw
 * CMDPROTO: int csa_dosetpw(void *source, int cargc, char **cargv);
 */

#include "../chanserv.h"
#include "../authlib.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csa_dosetpw(void *source, int cargc, char **cargv) {
  reguser *rup;
  nick *sender=source;

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "setpassword");
    return CMD_ERROR;
  }

  if (!(rup=findreguser(sender, cargv[0])))
    return CMD_ERROR;

  strncpy(rup->password,cargv[1],PASSLEN);
  rup->password[PASSLEN]='\0';
  chanservstdmessage(sender, QM_PWCHANGED);
  cs_log(sender,"SETPASSWORD OK username %s",rup->username);
  csdb_updateuser(rup);

  return CMD_OK;
}
