/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: setpassword
 * CMDLEVEL: QCMD_OPER
 * CMDARGS: 2
 * CMDDESC: Set a new password.
 * CMDFUNC: csa_dosetpw
 * CMDPROTO: int csa_dosetpw(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: setpassword <username> <password>
 * CMDHELP: Sets the password for the specified username.
 */

#include "../chanserv.h"
#include "../authlib.h"
#include "../../lib/irc_string.h"
#include <stdio.h>
#include <string.h>

int csa_dosetpw(void *source, int cargc, char **cargv) {
  nick *sender=source;
  reguser *rup, *vrup=getreguserfromnick(sender);

  if (cargc<2) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "setpassword");
    return CMD_ERROR;
  }

  if (!(rup=findreguser(sender, cargv[0])))
    return CMD_ERROR;

  if(UHasHelperPriv(rup)) {
    cs_log(sender,"GETPASSWORD FAILED username %s",rup->username);
    chanservwallmessage("%s (%s) just FAILED using SETPASSWORD on %s", sender->nick, vrup->username, rup->username);
    chanservsendmessage(sender, "Sorry, that user is privileged.");
    return CMD_ERROR;
  }

  cs_log(sender,"SETPASSWORD OK username %s",rup->username);
  chanservwallmessage("%s (%s) just used SETPASSWORD on %s", sender->nick, vrup->username, rup->username);

  if(rup->lastemail) {
    freesstring(rup->lastemail);
    rup->lastemail=NULL;
  }
  rup->lockuntil=0;

  csdb_accounthistory_insert(sender, rup->password, cargv[1], NULL, NULL);
  setpassword(rup, cargv[1]);
  csdb_updateuser(rup);

  chanservstdmessage(sender, QM_PWCHANGED);

  return CMD_OK;
}
