/* Automatically generated by refactor.pl.
 *
 *
 * CMDNAME: ticketauth
 * CMDLEVEL: QCMD_SECURE | QCMD_NOTAUTHED | QCMD_HIDDEN
 * CMDARGS: 1
 * CMDDESC: Authenticates you on the bot using a ticket.
 * CMDFUNC: csa_doticketauth
 * CMDPROTO: int csa_doticketauth(void *source, int cargc, char **cargv);
 * CMDHELP: Usage: ticketauth <ticket>
 * CMDHELP: This is an internal QuakeNet function, there's no point in
 * CMDHELP: asking for details on how it works cos' you'll not get any!
 */

#include "../chanserv.h"
#include <stdio.h>
#include <time.h>

int csa_completeauth(nick *sender, reguser *rup, char *authtype);

int csa_doticketauth(void *source, int cargc, char **cargv) {
  nick *sender = source;

  if(cargc!=1) {
    chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "ticketauth");
    return CMD_ERROR;
  }

  char *ticket = cargv[0];
  size_t ticket_len = strlen(ticket);

  if(ticket_len < 65) {
    chanservstdmessage(sender, QM_INVALIDHMAC);
    return CMD_ERROR;
  }

  char *digest = &ticket[ticket_len - 64];
  *(digest - 1) = '\0';

  int ret = csc_verifyqticket(ticket, digest);
  if(ret < 0) {
    chanservstdmessage(sender, QM_CONFIGURATIONERROR);
    return CMD_ERROR;
  } else if(ret > 0) {
    chanservstdmessage(sender, QM_INVALIDHMAC);
    return CMD_ERROR;
  }

  time_t logintimestamp, expiry;
  long uid;
  {
    intmax_t logintimestamp_i, expiry_i;
    if(sscanf(ticket, "%ld %jd %jd ", &uid, &logintimestamp_i, &expiry_i) != 3) {
      chanservstdmessage(sender, QM_NOTENOUGHPARAMS, "ticketauth");
      return CMD_ERROR;
    }
    logintimestamp = (time_t)logintimestamp_i;
    expiry = (time_t)expiry_i;
  }

  time_t t = time(NULL);
  if(t < logintimestamp) {
    chanservstdmessage(sender, QM_TICKETNOTYETVALID);
    return CMD_ERROR;
  }
  if(t > expiry) {
    chanservstdmessage(sender, QM_TICKETEXPIRED);
    return CMD_ERROR;
  }

  reguser *rup;
  if(!(rup=findreguserbyID(uid))) {
    chanservstdmessage(sender, QM_UNKNOWNUSER, "??");
    return CMD_ERROR;
  }

  if(rup->lastpasschange >= logintimestamp) {
    chanservstdmessage(sender, QM_PASSEMAILCHANGED);
    return CMD_ERROR;
  }

  return csa_completeauth(sender, rup, "TICKETAUTH");
}
